language: python
python:
    - "2.7"
    - "3.3"
    - "pypy"
install:
    - "pip install -r requirements.txt --use-mirrors"
    - "pip install mock httpretty"
before_script:
    - "pip install python-coveralls coverage"
script:
    - "coverage run runtests.py"
after_success:
    - "coveralls"
notifications:
    email: false
