language: python
python:
    - "2.7"
install:
    - "pip install -r requirements.txt --use-mirrors"
    - "pip install mock httpretty"
before_script:
    - "pip install python-coveralls coverage"
script:
    - "coverage run manage.py test filemaker"
after_success:
    - "coveralls"
notifications:
    email: false
